author = "mangkoran"
base_url = "https://foobar-zola.mangkoran.com"
build_search_index = false
compile_sass = false
taxonomies = [{ name = "tags" }]
title = "foobar-zola"

[markdown]
highlight_code = false

[extra]
[extra.navigation]
items = [
  { text = "Home", url = "/" },
  { text = "Blog", url = "/blog/" },
  # { name = "Tags", url = "/tags/" },
  { text = "About", url = "/about/" },
]
