name = "foobar-zola"
description = ""
license = "MIT"
homepage = "https://github.com/mangkoran/foobar-zola"
min_version = ""
demo = "https://foobar-zola.mangkoran.com"

[extra]
[extra.menus]
main = [
  { name = "Home", url = "" },
  { name = "Blog", url = "blog/" },
  # { name = "Tags", url = "tags/" },
  { name = "About", url = "about/" },
]

[author]
name = "mangkoran"
homepage = "https://blog.mangkoran.com"
